# Generated by Django 5.0.6 on 2024-07-02 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_manager', '0002_card_set_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_manager.collection'),
        ),
        migrations.AlterField(
            model_name='user',
            name='collection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='card_manager.collection'),
        ),
    ]
