# Generated by Django 5.0.6 on 2024-07-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_manager', '0003_alter_card_collection_alter_user_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(default='collection_name', max_length=255),
        ),
    ]
