# Generated by Django 5.0.6 on 2024-07-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_manager', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_discriminator',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_email',
            field=models.EmailField(default=None, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_username',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
