# Generated by Django 5.0.6 on 2024-07-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_manager', '0007_user_discord_discriminator_user_discord_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discord_discriminator',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord_email',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord_username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
