# Generated by Django 5.0.6 on 2024-06-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='collector_number',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='set',
            field=models.CharField(default='Set Name', max_length=255),
        ),
    ]
