# Generated by Django 5.0.6 on 2024-06-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_collector_number_card_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='scryfall_id',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
