name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          API_URL: ${{ secrets.API_URL }}
          PING_API: ${{ secrets.PING_API }}
          GET_CARD: ${{ secrets.GET_CARD }}
          GET_COLLECTION: ${{ secrets.GET_COLLECTION }}
          UPDATE_COLLECTION: ${{ secrets.UPDATE_COLLECTION }}
          CREATE_USER: ${{ secrets.CREATE_USER }}
          SCRYFALL_URL: ${{ secrets.SCRYFALL_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python manage.py test